[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
schnorr = { path = "../schnorr" }
rand_core = { version = "0.6", features = ["getrandom"] }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"
thiserror = "1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
serde_json = "1"
bincode = "1"

[[bench]]
name = "auth_benchmark"
harness = false